apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: develop-project
  namespace: argocd
spec:
  description: Develop Environment
  sourceRepos:
    - '*'
  destinations:
    - namespace: 'argocd'
      server: 'https://kubernetes.default.svc'
    - namespace: 'microservices'
      server: 'https://kubernetes.default.svc'
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'