environment: develop
spec:
  namespace: argocd
  project: develop-project
  destination:
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/tmtam612/cloud-mastery-iac.git
    targetRevision: develop