tag: 2.22.4
fullnameOverride: defectdojo
host: defectdojo.demo.localdev.me
site_url: https://defectdojo.demo.localdev.me
alternativeHosts:
  - defectdojo-django.defectdojo

initializer:
  # should be false after initial installation was performed
  run: true
django:
  ingress:
    enabled: true # change to 'false' for OpenShift
    activateTLS: false
  uwsgi:
    livenessProbe:
      # Enable liveness checks on uwsgi container. Those values are use on nginx readiness checks as well.
      # default value is 120, so in our case 20 is just fine
      initialDelaySeconds: 20