apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-apps
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    path: modules/k8s/helm-charts/argocd/argocd
    helm:
      valueFiles:
       - values/develop-values
      parameters: [ ]
    repoURL: https://github.com/tmtam612/cloud-mastery-iac.git
    targetRevision: develop
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - Validate=true
      - CreateNamespace=false
      - PrunePropagationPolicy=foreground
      - PruneLast=true  
