---
controller:
  ingressClassResource:
    name: nginx
  service:
    annotations:
      service.beta.kubernetes.io/azure-load-balancer-health-probe-request-path: /healthz
      service.beta.kubernetes.io/azure-load-balancer-resource-group: "${resource_group}"
      service.beta.kubernetes.io/azure-pip-name: "${pip_name}"
      service.beta.kubernetes.io/azure-dns-label-name: "${dns_name}"
  # Required for ACME
  watchIngressWithoutClass: true
  extraArgs:
    ingress-class: nginx
