apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloud-mastery-notification
  namespace: {{ .Values.spec.namespace }}
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: microservices
    server: {{ .Values.spec.destination.server }}
  project: {{ .Values.spec.project }}
  source:
    path: modules/k8s/helm-charts/argocd/argo-app
    helm:
      valueFiles:
        - values/{{ .Values.environment }}/notification-values.yaml
      parameters: [ ]
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
  syncPolicy:
    automated:
      prune: true
      allowEmpty: true
      selfHeal: true
    syncOptions:
      - allowEmpty=true
      - CreateNamespace=true