apiVersion: v1
kind: Namespace
metadata:
  name: self-hosted-runners
---
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: dos-box-runner
  namespace: self-hosted-runners
spec:
  replicas: 1
  template:
    spec:
      ephemeral: true
      repository: tmtam612/cloud-mastery-iac
      tolerations:
      - key: virtual-kubelet.io/provider
        operator: "Exists"
        effect: NoSchedule
---
apiVersion: actions.summerwind.dev/v1alpha1
kind: HorizontalRunnerAutoscaler
metadata:
  name: dos-box-runner-autoscaler
  namespace: self-hosted-runners
spec:
  scaleDownDelaySecondsAfterScaleOut: 300
  scaleTargetRef:
    kind: RunnerDeployment
    name: dos-box-runner
  minReplicas: 0
  maxReplicas: 5
  metrics:
  - type: TotalNumberOfQueuedAndInProgressWorkflowRuns
    scaleUpThreshold: '1'
    scaleDownThreshold: '0'
    scaleUpFactor: '2'
    scaleDownFactor: '0.5'        