apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: topx-team-certificate
  namespace: ingress-service
spec:
  # name of the tls secret to store
  # the generated certificate/key pair
  secretName: topx-team-certificate-secret
  isCA: true
  issuerRef:
    # issuer created in step 1
    name: letsencrypt-staging
    kind: ClusterIssuer
    group: cert-manager.io
  dnsNames:
  # one or more fully-qualified domain name
  # can be defined here
  - "*.topx.team"
