apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
  namespace: ingress-controller
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: tmtam612@gmail.com
    privateKeySecretRef:
      name: letsencrypt-staging
    solvers:
    - dns01:
        azureDNS:
          hostedZoneName: $dns_zone_name
          resourceGroupName: $resource_group
          subscriptionID: $subscription_id
          environment: AzurePublicCloud
          managedIdentity:
            clientID: $client_id
---
# apiVersion: cert-manager.io/v1
# kind: ClusterIssuer
# metadata:
#   name: letsencrypt-production
# spec:
#   acme:
#     server: https://acme-v02.api.letsencrypt.org/directory
#     email: tmtam612@gmail.com
#     privateKeySecretRef:
#       name: letsencrypt-production
#     solvers:
#     - http01:
#         ingress:
#           class: nginx
#           podTemplate:
#             spec:
#               nodeSelector:
#                 "kubernetes.io/os": linux
