name: 'Terraform'

on:
  push:
    branches: [ "develop", "main" ]
env:
  ARM_CLIENT_ID: ${{secrets.AZURE_CLIENT_ID}}
  ARM_CLIENT_SECRET: ${{secrets.AZURE_CLIENT_SECRET}}
  ARM_SUBSCRIPTION_ID: ${{secrets.AZURE_SUBSCRIPTION_ID}}
  ARM_TENANT_ID: ${{secrets.AZURE_TENANT_ID}}
  AZURE_CREDENTIALS: ${{secrets.AZURE_CREDENTIALS}}
  ROOT_PATH: '${{github.workspace}}'
  DEVELOP_WORKPLACE: 'develop'
  ACCEPTANCE_WORKPLACE: 'acceptance'
  PRODUCTION_WORKPLACE: 'production'
  ENVIRONMENT_DEV_TFVARS: '${{github.workspace}}/environment/dev.tfvars'
  ENVIRONMENT_TEST_TFVARS: '${{github.workspace}}/environment/test.tfvars'
  ENVIRONMENT_PROD_TFVARS: '${{github.workspace}}/environment/prod.tfvars'

permissions:
  id-token: write
  contents: read

jobs:
  terraform_plan_dev:
    name: 'Terraform Plan dev'
    runs-on: ubuntu-latest
    environment: develop
    # Use the Bash shell regardless whether the GitHub Actions runner is self-hosted, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v3
      
    # https://github.com/actions/setup-node
    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    # Install the latest version of Terraform CLI and configure the Terraform CLI configuration file with a Terraform Cloud user API token
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.7.3

    - name: Log in with Azure
      uses: azure/login@v1
      with:
        creds: '${{ secrets.AZURE_CREDENTIALS }}'

    # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
    - name: Terraform Init
      run: terraform init
      working-directory: ${{env.ROOT_PATH}}

    - name: Select Workspace
      run: terraform workspace select ${{env.DEVELOP_WORKPLACE}} || terraform workspace new  ${{env.DEVELOP_WORKPLACE}}
      working-directory: ${{env.ROOT_PATH}}

    # Checks that all Terraform configuration files adhere to a canonical format
    - name: Terraform Format
      run: terraform fmt -check
      working-directory: ${{env.ROOT_PATH}}

    # Validate all terraform configuation files
    - name: Terraform Validate
      run: terraform validate
      working-directory: ${{env.ROOT_PATH}}

    # Generates an execution plan for Terraform
    - name: Terraform Plan
      run: terraform plan --var-file=${{env.ENVIRONMENT_DEV_TFVARS}} --out tfplan.binary
      working-directory: ${{env.ROOT_PATH}}

    - name: Set up Python 3.8
      uses: actions/setup-python@v4
      with:
        python-version: 3.8

    - name: Install checkov
      run: pip3 install checkov

    - name: create tfplan.json file
      run: terraform show -json tfplan.binary > jq tfplan.json
      working-directory: ${{env.ROOT_PATH}}

    - name: scanning
      run: checkov -f tfplan.json
      working-directory: ${{env.ROOT_PATH}}
      # id: checkov
      # uses: bridgecrewio/checkov-action@master
      # with:
      #     directory: ${{env.ROOT_PATH}}
      #     # This will add both a CLI output to the console and create a results.sarif file
      #     output_format: cli,sarif
      #     output_file_path: console,results.sarif
      #     file: ${{env.ROOT_PATH}}/tfplan.json
      #     log_level: DEBUG
      #     soft_fail: false
      #     quiet: true

  terraform_apply_dev:
    name: 'Terraform Apply dev'
    needs: [terraform_plan_dev]
    runs-on: ubuntu-latest
    environment: develop
    
    defaults:
      run:
        shell: bash

    steps:    
    - name: Checkout
      uses: actions/checkout@v3

    - name: Log in with Azure
      uses: azure/login@v1
      with:
        creds: '${{ secrets.AZURE_CREDENTIALS }}'

    # https://github.com/actions/setup-node
    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.7.3

    - name: Terraform Init
      run: terraform init
      working-directory: ${{ env.ROOT_PATH }}

    - name: Select Workspace
      run: terraform workspace select ${{env.DEVELOP_WORKPLACE}} || terraform workspace new  ${{env.DEVELOP_WORKPLACE}}
      working-directory: ${{env.ROOT_PATH}}

    - name: Terraform Apply
      run: terraform apply -auto-approve --var-file=${{env.ENVIRONMENT_DEV_TFVARS}}
      if: ${{inputs.tf_destroy}} == false
      working-directory: ${{ env.ROOT_PATH }}

  terraform_plan_test:
    if: github.ref == 'refs/heads/develop' || github.ref == 'refs/heads/main'
    needs: [terraform_apply_dev]
    name: 'Terraform Plan Test'
    runs-on: ubuntu-latest
    environment: develop
    # Use the Bash shell regardless whether the GitHub Actions runner is self-hosted, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v3

    - name: Log in with Azure
      uses: azure/login@v1
      with:
        creds: '${{ secrets.AZURE_CREDENTIALS }}'

    # https://github.com/actions/setup-node
    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    # Install the latest version of Terraform CLI and configure the Terraform CLI configuration file with a Terraform Cloud user API token
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.7.3

    # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
    - name: Terraform Init
      run: terraform init
      working-directory: ${{env.ROOT_PATH}}
      
    - name: Select Workspace
      run: terraform workspace select ${{env.ACCEPTANCE_WORKPLACE}} || terraform workspace new  ${{env.ACCEPTANCE_WORKPLACE}}
      working-directory: ${{env.ROOT_PATH}}

    # Checks that all Terraform configuration files adhere to a canonical format
    - name: Terraform Format
      run: terraform fmt -check
      working-directory: ${{env.ROOT_PATH}}

    # Validate all terraform configuation files
    - name: Terraform Validate
      run: terraform validate
      working-directory: ${{env.ROOT_PATH}}

    # Generates an execution plan for Terraform
    - name: Terraform Plan
      run: terraform plan --var-file=${{env.ENVIRONMENT_TEST_TFVARS}}
      working-directory: ${{env.ROOT_PATH}}

  terraform_apply_test:
    if: github.ref == 'refs/heads/develop' || github.ref == 'refs/heads/main'
    name: 'Terraform Apply Test'
    needs: [terraform_plan_test]
    runs-on: ubuntu-latest
    environment: develop
    
    defaults:
      run:
        shell: bash

    steps:    
    - name: Checkout
      uses: actions/checkout@v3

    - name: Log in with Azure
      uses: azure/login@v1
      with:
        creds: '${{ secrets.AZURE_CREDENTIALS }}'

    # https://github.com/actions/setup-node
    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.7.3

    - name: Terraform Init
      run: terraform init
      working-directory: ${{ env.ROOT_PATH }}

    - name: Select Workspace
      run: terraform workspace select ${{env.ACCEPTANCE_WORKPLACE}} || terraform workspace new  ${{env.ACCEPTANCE_WORKPLACE}}
      working-directory: ${{env.ROOT_PATH}}

    - name: Terraform Apply
      run: terraform apply -auto-approve --var-file=${{env.ENVIRONMENT_TEST_TFVARS}}
      if: ${{inputs.tf_destroy}} == false
      working-directory: ${{ env.ROOT_PATH }}

  terraform_plan_prod:
    if: github.ref == 'refs/heads/main'
    needs: [terraform_apply_test]
    name: 'Terraform Plan Prod'
    runs-on: ubuntu-latest
    environment: develop
    # Use the Bash shell regardless whether the GitHub Actions runner is self-hosted, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v3
    
    - name: Log in with Azure
      uses: azure/login@v1
      with:
        creds: '${{ secrets.AZURE_CREDENTIALS }}' 

    # https://github.com/actions/setup-node
    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    # Install the latest version of Terraform CLI and configure the Terraform CLI configuration file with a Terraform Cloud user API token
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.7.3

    # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
    - name: Terraform Init
      run: terraform init
      working-directory: ${{env.ROOT_PATH}}

    - name: Select Workspace
      run: terraform workspace select ${{env.PRODUCTION_WORKPLACE}} || terraform workspace new  ${{env.PRODUCTION_WORKPLACE}}
      working-directory: ${{env.ROOT_PATH}}

    # Checks that all Terraform configuration files adhere to a canonical format
    - name: Terraform Format
      run: terraform fmt -check
      working-directory: ${{env.ROOT_PATH}}

    # Validate all terraform configuation files
    - name: Terraform Validate
      run: terraform validate
      working-directory: ${{env.ROOT_PATH}}

    # Generates an execution plan for Terraform
    - name: Terraform Plan
      run: terraform plan --var-file=${{env.ENVIRONMENT_PROD_TFVARS}}
      working-directory: ${{env.ROOT_PATH}}

  terraform_apply_prod:
    if: github.ref == 'refs/heads/main'
    name: 'Terraform Apply Prod'
    needs: [terraform_plan_prod]
    runs-on: ubuntu-latest
    environment: develop
    
    defaults:
      run:
        shell: bash

    steps:    
    - name: Checkout
      uses: actions/checkout@v3

    - name: Log in with Azure
      uses: azure/login@v1
      with:
        creds: '${{ secrets.AZURE_CREDENTIALS }}'

    # https://github.com/actions/setup-node
    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.7.3

    - name: Terraform Init
      run: terraform init
      working-directory: ${{ env.ROOT_PATH }}
      
    - name: Select Workspace
      run: terraform workspace select ${{env.PRODUCTION_WORKPLACE}} || terraform workspace new  ${{env.PRODUCTION_WORKPLACE}}
      working-directory: ${{env.ROOT_PATH}}

    - name: Terraform Apply
      run: terraform apply -auto-approve --var-file=${{env.ENVIRONMENT_PROD_TFVARS}}
      if: ${{inputs.tf_destroy}} == false
      working-directory: ${{ env.ROOT_PATH }}
